In [64]:
import numpy as np
import pandas as pd
import pickle
from random import gauss

In [26]:
a = [gauss(1.5, 2) for i in range(1000000)]

In [27]:
mkdir data 

In [28]:
path = './data/'

In [29]:
pkl_file = open(path+'data.pkl', 'w')

In [30]:
%time pickle.dump(a, pkl_file)

CPU times: user 5.49 s, sys: 95.7 ms, total: 5.58 s
Wall time: 5.8 s


In [31]:
pkl_file

<open file './data/data.pkl', mode 'w' at 0x104432270>

In [32]:
pkl_file.close()

In [33]:
ll $path*

-rw-r--r--  1 shaolongchen  staff  20971287 May 24 20:05 ./data/data.pkl


In [34]:
pkl_file = open(path+'data.pkl', 'r')

In [35]:
%time b = pickle.load(pkl_file)

CPU times: user 4.7 s, sys: 57.7 ms, total: 4.76 s
Wall time: 4.79 s


In [36]:
b[:5]

[-1.2716919570693959,
 2.781850283444185,
 2.2526975434782948,
 0.46759556125849433,
 0.309300613840493]

In [37]:
a[:5]

[-1.2716919570693959,
 2.781850283444185,
 2.2526975434782948,
 0.46759556125849433,
 0.309300613840493]

In [38]:
np.allclose(np.array(a), np.array(b))

True

In [39]:
np.sum(np.array(a)-np.array(b))

0.0

In [40]:
pkl_file = open(path+'data.pkl', 'w')

In [41]:
%time pickle.dump(np.array(a), pkl_file)

CPU times: user 836 ms, sys: 71.7 ms, total: 908 ms
Wall time: 917 ms


In [43]:
%time pickle.dump(np.array(a)**2, pkl_file)

CPU times: user 760 ms, sys: 64.1 ms, total: 824 ms
Wall time: 844 ms


In [44]:
pkl_file.close()

In [45]:
ll $path*

-rw-r--r--  1 shaolongchen  staff  44087251 May 24 20:12 ./data/data.pkl


In [52]:
pkl_file = open(path+'data.pkl', 'r')

In [53]:
x = pickle.load(pkl_file)
x

array([-1.27169196,  2.78185028,  2.25269754, ...,  0.62528649,
       -0.55918085,  3.15259636])

In [54]:
y = pickle.load(pkl_file)
y

array([ 1.61720043,  7.738691  ,  5.07464622, ...,  0.39098319,
        0.31268323,  9.93886381])

In [55]:
pkl_file.close()

In [56]:
pkl_file = open(path+'data.pkl', 'w')
pickle.dump({'x': x, 'y': y}, pkl_file)
pkl_file.close()

In [57]:
pkl_file = open(path+'data.pkl', 'r')
data = pickle.load(pkl_file)
pkl_file.close()
for key in data.keys():
    print key, data[key][:4]

y [ 1.61720043  7.738691    5.07464622  0.21864561]
x [-1.27169196  2.78185028  2.25269754  0.46759556]


In [60]:
for k, v in data.items():
    print k,v[:4]

y [ 1.61720043  7.738691    5.07464622  0.21864561]
x [-1.27169196  2.78185028  2.25269754  0.46759556]


In [61]:
!rm -f $path*

In [62]:
rows = 5000
a = np.random.standard_normal((rows, 5))

In [63]:
a.round(4)

array([[-0.0705,  0.0398,  0.0616,  0.244 , -0.1183],
       [ 0.4024, -1.5562, -0.646 , -0.3971, -1.0358],
       [-0.4401, -1.2726,  0.1632, -0.4378,  1.6241],
       ..., 
       [-0.9491, -0.8752, -0.8907, -0.752 , -0.2308],
       [-0.0517, -0.7585,  1.1901,  1.8466, -0.9697],
       [-0.5013,  0.9195,  0.7563,  1.0341,  0.3353]])

In [66]:
t = pd.date_range(start='2014/1/1', periods=rows, freq='H')

In [67]:
t

DatetimeIndex(['2014-01-01 00:00:00', '2014-01-01 01:00:00',
               '2014-01-01 02:00:00', '2014-01-01 03:00:00',
               '2014-01-01 04:00:00', '2014-01-01 05:00:00',
               '2014-01-01 06:00:00', '2014-01-01 07:00:00',
               '2014-01-01 08:00:00', '2014-01-01 09:00:00',
               ...
               '2014-07-27 22:00:00', '2014-07-27 23:00:00',
               '2014-07-28 00:00:00', '2014-07-28 01:00:00',
               '2014-07-28 02:00:00', '2014-07-28 03:00:00',
               '2014-07-28 04:00:00', '2014-07-28 05:00:00',
               '2014-07-28 06:00:00', '2014-07-28 07:00:00'],
              dtype='datetime64[ns]', length=5000, freq='H')

In [73]:
csv_file = open(path+'data.csv', 'w')

In [74]:
header = 'data,no1,no2,no3,no4,no5\n'
csv_file.write(header)

In [76]:
for t_, (no1, no2, no3, no4, no5) in zip(t, a):
    s = '%s,%f,%f,%f,%f,%f\n' % (t_, no1, no2, no3, no4, no5)
    csv_file.write(s)
csv_file.close()

In [77]:
ll $path*

-rw-r--r--  1 shaolongchen  staff  674607 May 24 20:34 ./data/data.csv


In [78]:
csv_file = open(path+'data.csv', 'r')
for i in range(5):
    print csv_file.readline(),

data,no1,no2,no3,no4,no5
2014-01-01 00:00:00,-0.070524,0.039786,0.061602,0.244043,-0.118305
2014-01-01 01:00:00,0.402436,-1.556201,-0.646024,-0.397051,-1.035789
2014-01-01 02:00:00,-0.440071,-1.272560,0.163231,-0.437831,1.624056
2014-01-01 03:00:00,-0.368087,-0.661043,1.534949,0.127373,1.296445


In [79]:
csv_file = open(path+'data.csv', 'r')
content = csv_file.readlines()
for line in content[:5]:
    print line

data,no1,no2,no3,no4,no5

2014-01-01 00:00:00,-0.070524,0.039786,0.061602,0.244043,-0.118305

2014-01-01 01:00:00,0.402436,-1.556201,-0.646024,-0.397051,-1.035789

2014-01-01 02:00:00,-0.440071,-1.272560,0.163231,-0.437831,1.624056

2014-01-01 03:00:00,-0.368087,-0.661043,1.534949,0.127373,1.296445



In [80]:
csv_file.close()
!rm -f $path*

In [102]:
import sqlite3 as sq3

In [103]:
query = 'CREATE TABLE numbs (Date date, No1 real, No2 real)'

In [104]:
con = sq3.connect(path+'numbs.db')

In [105]:
con.execute(query)

In [106]:
con.commit()

In [107]:
import datetime as dt

In [108]:
con.execute('INSERT INTO numbs VALUES(?, ?, ?)', (dt.datetime.now(), 0.12, 7.3))

In [109]:
data = np.random.standard_normal((10000, 2)).round(5)

In [110]:
for row in data:
    con.execute('INSERT INTO numbs VALUES(?, ?, ?)', (dt.datetime.now(), row[0], row[1]))
con.commit()

In [111]:
con.execute('SELECT * FROM numbs').fetchmany(10)

[(u'2017-05-24 20:51:02.668289', 0.12, 7.3),
 (u'2017-05-24 20:51:09.258172', 0.34738, -0.9713),
 (u'2017-05-24 20:51:09.258476', 0.03794, -0.50022),
 (u'2017-05-24 20:51:09.258539', -1.62785, -0.77952),
 (u'2017-05-24 20:51:09.258589', 0.02433, 0.1472),
 (u'2017-05-24 20:51:09.258709', -2.82959, 1.13986),
 (u'2017-05-24 20:51:09.258782', 0.59489, -0.08416),
 (u'2017-05-24 20:51:09.258837', -1.40731, -1.32493),
 (u'2017-05-24 20:51:09.258899', -0.46339, -0.70127),
 (u'2017-05-24 20:51:09.258949', -1.3489, 0.62401)]

In [112]:
pointer = con.execute('SELECT * FROM numbs')
for i in range(3):
    print pointer.fetchone()

(u'2017-05-24 20:51:02.668289', 0.12, 7.3)
(u'2017-05-24 20:51:09.258172', 0.34738, -0.9713)
(u'2017-05-24 20:51:09.258476', 0.03794, -0.50022)


In [113]:
con.close()
!rm -f $path*

In [114]:
import numpy as np

In [115]:
dtimes = np.arange('2015-01-01 10:00:00', '2021-12-31 22:00:00', dtype='datetime64[m]')
len(dtimes)

3681360

In [117]:
dty = np.dtype([('Date', 'datetime64[m]'), ('No1', 'f'), ('No2', 'f')])
data = np.zeros(len(dtimes), dtype=dty)

In [118]:
data['Date'] = dtimes

In [120]:
a = np.random.standard_normal((len(dtimes), 2)).round(5)
data['No1'] = a[:, 0]
data['No2'] = a[:, 1]

In [121]:
%time np.save(path+'array', data)

CPU times: user 4.88 ms, sys: 133 ms, total: 138 ms
Wall time: 199 ms


In [122]:
ll $path*

-rw-r--r--  1 shaolongchen  staff  58901888 May 24 20:57 ./data/array.npy


In [123]:
%time np.load(path+'array.npy')

CPU times: user 2.68 ms, sys: 49 ms, total: 51.7 ms
Wall time: 811 ms


array([ (datetime.datetime(2015, 1, 1, 10, 0), 0.7728800177574158, -0.3847300112247467),
       (datetime.datetime(2015, 1, 1, 10, 1), -0.7022200226783752, 1.2079800367355347),
       (datetime.datetime(2015, 1, 1, 10, 2), -0.8108900189399719, -0.19157999753952026),
       ...,
       (datetime.datetime(2021, 12, 31, 21, 57), 1.5415500402450562, -0.6472100019454956),
       (datetime.datetime(2021, 12, 31, 21, 58), 1.8814400434494019, -1.176650047302246),
       (datetime.datetime(2021, 12, 31, 21, 59), 1.0594600439071655, -0.5235700011253357)], 
      dtype=[('Date', '<M8[m]'), ('No1', '<f4'), ('No2', '<f4')])

In [124]:
data = np.random.standard_normal((10000, 6000))

In [125]:
%time np.save(path+'array', data)

CPU times: user 33.1 ms, sys: 5.34 s, total: 5.37 s
Wall time: 6.86 s


In [126]:
ll $path*

-rw-r--r--  1 shaolongchen  staff  480000080 May 24 20:59 ./data/array.npy


In [127]:
%time np.load(path+'array.npy')

CPU times: user 2.4 ms, sys: 633 ms, total: 636 ms
Wall time: 1.86 s


array([[ 0.98065305, -0.33223401,  0.45933912, ...,  2.56426395,
        -0.33936563, -0.52410328],
       [ 0.80081149,  1.687483  ,  0.83063852, ...,  2.04699163,
        -0.54600533, -1.37468229],
       [-2.20126577,  0.84657452, -2.64239456, ...,  0.73202456,
        -1.39536448, -0.75716483],
       ..., 
       [ 0.55231287,  1.2857015 ,  0.16457321, ...,  1.27261675,
         1.29951662, -0.26446683],
       [ 0.67323342, -1.42295118,  0.47752731, ...,  0.27478281,
         0.16155138,  0.06478749],
       [ 1.78114415,  0.88774113, -1.358191  , ...,  0.71235431,
         0.18555603, -0.21112835]])

In [128]:
datta = 0.0
!rm -f $path*